spring.application.name=portfolio
#
#spring.datasource.url=jdbc:mysql://localhost:3306/awfisdb

spring.datasource.url=jdbc:mysql://database-1.c528y4cqqb5x.ap-south-1.rds.amazonaws.com/awsfisdb
spring.datasource.username=root
#spring.datasource.password=JainagBhu01@Admin
spring.datasource.password=4e9ihnK7M8nySfu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect